<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BiomorphRandomizer</RootNamespace>
    <!-- <Nullable>enable</Nullable> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>lib\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>lib\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>lib\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>lib\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>lib\Il2Cppmscorlib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
